### ISSUE TITLE
database admin y rest api devuelven "page not found"

### ISSUE THREAD

**Issue by palmoreck** [jdonlucas/selia-irekua-docker-dev#1]
Hola @jdonlucas !

Instalé `docker` y `docker-compose` en una instancia de AWS `m5.xlarge` con un volumen de 50 GB y `ubuntu-20.4` utilizando el siguiente *script*:

```
#!/bin/bash
region=us-west-2
name_instance=irekua-db-rest-selia
user=ubuntu
##System update
export DEBIAN_FRONTEND=noninteractive
apt-get update -yq
##Install awscli
apt-get install -y python3-pip && pip3 install --upgrade pip
pip3 install awscli --upgrade
##Tag instance
INSTANCE_ID=$(curl -s http://instance-data/latest/meta-data/instance-id)
PUBLIC_IP=$(curl -s http://instance-data/latest/meta-data/public-ipv4)
aws ec2 create-tags --resources $INSTANCE_ID --tag Key=Name,Value=$name_instance-$PUBLIC_IP --region=$region
apt-get install -y apt-transport-https ca-certificates curl software-properties-common
#install docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
apt-get update -yq
apt-get install -y docker-ce
service docker start
groupadd docker
usermod -aG docker ubuntu && newgrp docker
#install docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
```

Una vez en la instancia ejecuté lo siguiente:

```
git clone https://github.com/jdonlucas/irekua-docker-dev.git

cd irekua-docker-dev/

bash get-repos.sh

docker-compose build

docker-compose run database python manage.py check

docker-compose run database python manage.py migrate

docker-compose run database python manage.py createsuperuser

docker-compose up
```

Selia sí se levantó, pero DB admin y res api no. Adjunto *screenshots*

![Captura de pantalla 2021-07-06 a las 10 13 53 a m](https://user-images.githubusercontent.com/3290689/124646955-ebd59c80-de5a-11eb-92be-f29256dbc8b9.png)

![Captura de pantalla 2021-07-06 a las 10 13 55 a m](https://user-images.githubusercontent.com/3290689/124646968-f132e700-de5a-11eb-8b1e-da1fa91c6619.png)

![Captura de pantalla 2021-07-06 a las 10 13 56 a m](https://user-images.githubusercontent.com/3290689/124646976-f4c66e00-de5a-11eb-8d6c-8115f12e25ae.png)

![Captura de pantalla 2021-07-06 a las 10 14 32 a m](https://user-images.githubusercontent.com/3290689/124646986-f7c15e80-de5a-11eb-9434-9d2e8f36017a.png)

Sigo pendiente.

👋🏾

**Comment by jdonlucas** [comment]
Que tal @palmoreck, la base de datos de irekua y su rest api tienen rutas específicas para acceder al admin y a cada uno de los endpoints.  Por default, el root del puerto 5002 donde corre la base de datos no tiene nada y si se accede a el, muestra la clásica pantalla amarilla de django, con el error 404. Sin embargo funciona así por que no esta pensado que se acceda a la base de datos desde el root, si no la ruta

       localhost:5002/admin

lo mismo sucede con el api, pero este tiene distintos puntos de acceso:

      localhost:5001/api/schemas/v1/
      localhost:5001/api/terms/v1/
      localhost:5001/api/operations/v1/
      localhost:5001/api/items/v1/
      localhost:5001/api/geo/v1/
      localhost:5001/api/devices/v1/
      localhost:5001/api/annotations/v1/
      localhost:5001/api/collections/v1/
      localhost:5001/api/models/v1/
      localhost:5001/api/visualizers/v1/

adicionalmente, también puedes acceder al admin a través del contenedor del api:

      localhost:5001/admin

cualquier duda sigo pendiente! 👋

**Comment by palmoreck** [comment]
Excelente, gracias @jdonlucas
